name: Examples
on:
  push:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

jobs:
  examples:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: get NASM
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install nasm

      - name: manual
        run: odin run examples/manual -vet -strict-style
      - name: manual debug
        run: odin run examples/manual -vet -strict-style -debug

      - name: allocator
        run: odin run examples/allocator -vet -strict-style
      - name: allocator debug
        run: odin run examples/allocator -vet -strict-style -debug
