name: Examples
on:
  push:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

jobs:
  examples:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: laytan/setup-odin@v1

      - name: manual
        run: odin run examples/manual -vet -strict-style
      - name: manual debug
        run: odin run examples/manual -vet -strict-style -debug

      - name: allocator
        run: odin run examples/allocator -vet -strict-style
      - name: allocator debug
        run: odin run examples/allocator -vet -strict-style -debug

      - name: segfault
        shell: bash
        run: |
          odin run examples/segfault -vet -strict-style
          code=$?
          if [ $code -eq 11 ]; then
            exit 0
          else
            echo "Exit code $code"
            exit 1
          fi

      - name: segfault debug
        shell: bash
        run: |
          odin run examples/segfault -vet -strict-style -debug
          code=$?
          if [ $code -eq 11 ]; then
            exit 0
          else
            echo "Exit code $code"
            exit 1
          fi

      - name: assert
        shell: bash
        run: |
          odin run examples/assert_backtrace -vet -strict-style
          code=$?
          if [ $code -eq 5 ]; then
            exit 0
          else
            echo "Exit code $code"
            exit 1
          fi

      - name: assert backtrace debug
        shell: bash
        run: |
          odin run examples/assert_backtrace -vet -strict-style -debug
          code=$?
          if [ $code -eq 5 ]; then
            exit 0
          else
            echo "Exit code $code"
            exit 1
          fi
